export const CHANGE_LOGIN_STATUS = 'CHANGE_LOGIN_STATUS';
export const SHOW_MODAL = 'SHOW_MODAL';
export const SAVE_USER_DATA = 'SAVE_USER_DATA';
export const GET_USER_LISTS = 'GET_USER_LISTS';
export const SAVE_USER_LISTS = 'SAVE_USER_LISTS';
export const SAVE_SHARED_USER_LISTS = 'SAVE_SHARED_USER_LISTS';
export const SET_LOADING_STATUS = 'SET_LOADING_STATUS';


